[2020-01-03 20:16:04,275] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:73} WARNING - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/auth/register?", "request": {"full_name": "Dobleh Jamal", "email": "youdontsayhuman@gmail.com", "username": "Dobleh99", "password": "rahasia123"}, "response": {"message": "Internal Server Error"}}
[2020-01-03 20:18:59,173] {/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/auth/resource.py", line 39, in post
    signature = gmail.get_signature()
  File "/home/alta13/Documents/E-Commerce/TEESIGNR/gmail/gmail.py", line 110, in get_signature
    service = build('gmail', 'v1', credentials=creds)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/discovery.py", line 226, in build
    credentials=credentials)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/discovery.py", line 364, in build_from_document
    credentials = _auth.default_credentials()
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/_auth.py", line 42, in default_credentials
    credentials, _ = google.auth.default()
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/google/auth/_default.py", line 321, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2020-01-03 20:18:59,193] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:73} WARNING - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/auth/register?", "request": {"full_name": "Dobleh Jamal", "email": "youdontsayhuman@gmail.com", "username": "Dobleh99", "password": "rahasia123"}, "response": {"message": "Internal Server Error"}}
[2020-01-03 20:20:47,411] {/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/auth/resource.py", line 39, in post
    signature = gmail.get_signature()
  File "/home/alta13/Documents/E-Commerce/TEESIGNR/gmail/gmail.py", line 110, in get_signature
    service = build('gmail', 'v1', credentials=creds)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/discovery.py", line 226, in build
    credentials=credentials)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/discovery.py", line 364, in build_from_document
    credentials = _auth.default_credentials()
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/_auth.py", line 42, in default_credentials
    credentials, _ = google.auth.default()
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/google/auth/_default.py", line 321, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2020-01-03 20:20:47,445] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:73} WARNING - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/auth/register?", "request": {"full_name": "Dobleh Jamal", "email": "youdontsayhuman@gmail.com", "username": "Dobleh99", "password": "rahasia123"}, "response": {"message": "Internal Server Error"}}
[2020-01-03 20:21:39,811] {/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/auth/resource.py", line 39, in post
    signature = gmail.get_signature()
  File "/home/alta13/Documents/E-Commerce/TEESIGNR/gmail/gmail.py", line 110, in get_signature
    service = build('gmail', 'v1', credentials=creds)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/discovery.py", line 226, in build
    credentials=credentials)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/discovery.py", line 364, in build_from_document
    credentials = _auth.default_credentials()
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/_auth.py", line 42, in default_credentials
    credentials, _ = google.auth.default()
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/google/auth/_default.py", line 321, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2020-01-03 20:21:39,827] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:73} WARNING - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/auth/register?", "request": {"full_name": "Dobleh Jamal", "email": "youdontsayhuman@gmail.com", "username": "Dobleh99", "password": "rahasia123"}, "response": {"message": "Internal Server Error"}}
[2020-01-03 20:22:37,189] {/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /auth/register [POST]
Traceback (most recent call last):
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/auth/resource.py", line 39, in post
    signature = gmail.get_signature()
  File "/home/alta13/Documents/E-Commerce/TEESIGNR/gmail/gmail.py", line 110, in get_signature
    service = build('gmail', 'v1', credentials=creds)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/discovery.py", line 226, in build
    credentials=credentials)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/discovery.py", line 364, in build_from_document
    credentials = _auth.default_credentials()
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/googleapiclient/_auth.py", line 42, in default_credentials
    credentials, _ = google.auth.default()
  File "/home/alta13/Documents/E-Commerce/portofolio_env/lib/python3.6/site-packages/google/auth/_default.py", line 321, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2020-01-03 20:22:37,221] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:73} WARNING - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/auth/register?", "request": {"full_name": "Dobleh Jamal", "email": "youdontsayhuman@gmail.com", "username": "Dobleh99", "password": "rahasia123"}, "response": {"message": "Internal Server Error"}}
[2020-01-03 20:27:16,775] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:64} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/auth/register?", "request": {"full_name": "Dobleh Jamal", "email": "youdontsayhuman@gmail.com", "username": "Dobleh99", "password": "rahasia123"}, "response": {"status": "register berhasil", "user": {"id": 8, "full_name": "Dobleh Jamal", "email": "youdontsayhuman@gmail.com", "username": "Dobleh99", "password": "7f95b733f4210c71482904eb422143f8", "designer_status": false}}}
[2020-01-03 20:36:50,694] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:64} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/auth/register?", "request": {"full_name": "Mohammad Daffa", "email": "daffa@alterra.id", "username": "Fadafuq", "password": "rahasia123"}, "response": {"status": "register berhasil", "user": {"id": 9, "full_name": "Mohammad Daffa", "email": "daffa@alterra.id", "username": "Fadafuq", "password": "7f95b733f4210c71482904eb422143f8", "designer_status": false}}}
[2020-01-03 22:49:49,807] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:73} WARNING - REQUEST_LOG	{"status_code": 404, "method": "GET", "code": "404 NOT FOUND", "uri": "/login?", "request": {"email": "daffa@alterra.com"}, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2020-01-03 22:52:17,494] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:73} WARNING - REQUEST_LOG	{"status_code": 401, "method": "GET", "code": "401 UNAUTHORIZED", "uri": "/auth/reset?", "request": {"email": "daffa@alterra.com"}, "response": {"status": "Gagal", "message": "E-mail tidak terdaftar"}}
[2020-01-03 22:52:29,024] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:64} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/auth/reset?", "request": {"email": "daffa@alterra.id"}, "response": {"status": "Password baru sudah terkirim ke email"}}
[2020-01-03 22:53:38,020] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:64} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/auth/login?", "request": {"email": "daffa@alterra.id", "password": "Ku5f0E"}, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgwNjY4MTgsIm5iZiI6MTU3ODA2NjgxOCwianRpIjoiNzBmY2ZhYWUtMmY1Yy00ODI0LWIxZGMtNmQ1ZThjMTNlODg0IiwiZXhwIjoxNTc4MTUzMjE4LCJpZGVudGl0eSI6IkZhZGFmdXEiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MiLCJ1c2VyX2NsYWltcyI6eyJpZCI6OSwiZnVsbF9uYW1lIjoiTW9oYW1tYWQgRGFmZmEiLCJlbWFpbCI6ImRhZmZhQGFsdGVycmEuaWQiLCJ1c2VybmFtZSI6IkZhZGFmdXEiLCJkZXNpZ25lcl9zdGF0dXMiOmZhbHNlfX0.wbJ7yxVh8raNGOb6Mwbkd127NYmcemkDXABM8wLOq0A"}}
[2020-01-03 22:55:22,669] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:64} INFO - REQUEST_LOG	{"status_code": 200, "method": "PATCH", "code": "200 OK", "uri": "/user/edit?", "request": {"old_password": "Ku5f0E", "new_password": "rahasia123"}, "response": {"status": "password berhasil diubah"}}
[2020-01-03 22:55:31,019] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:73} WARNING - REQUEST_LOG	{"status_code": 401, "method": "POST", "code": "401 UNAUTHORIZED", "uri": "/auth/login?", "request": {"email": "daffa@alterra.id", "password": "Ku5f0E"}, "response": {"status": "UNAUTHORIZED", "message": "Password atau Email salah"}}
[2020-01-03 22:55:39,438] {/home/alta13/Documents/E-Commerce/TEESIGNR/blueprints/__init__.py:64} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/auth/login?", "request": {"email": "daffa@alterra.id", "password": "rahasia123"}, "response": {"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzgwNjY5MzksIm5iZiI6MTU3ODA2NjkzOSwianRpIjoiOGQ0YjkyOTYtODkxYS00MjM1LThhNTAtMGIyMmU3OTdjY2E1IiwiZXhwIjoxNTc4MTUzMzM5LCJpZGVudGl0eSI6IkZhZGFmdXEiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MiLCJ1c2VyX2NsYWltcyI6eyJpZCI6OSwiZnVsbF9uYW1lIjoiTW9oYW1tYWQgRGFmZmEiLCJlbWFpbCI6ImRhZmZhQGFsdGVycmEuaWQiLCJ1c2VybmFtZSI6IkZhZGFmdXEiLCJkZXNpZ25lcl9zdGF0dXMiOmZhbHNlfX0.CqPBDxhEJOHAnoGgkj9KN66XIsc20Q2AWTy2354lOek"}}
